## Question 1
#(1a) create a dataset of 998 variables
set.seed(2201)   #set the randomization seed
x <- rnorm(998)  #generate 998 value of x from a normal distribution
y = -10*x + 22 + rnorm(998, 1,0.5) 
#the data-generating equation: y = -10*x + 22 + error
#normal error term is generated by rnorm
dt <- data.frame(x,y)   #create the dataframe
lm.dt <-lm(y~x, data=dt)
summary(lm.dt)

# (1b) adding two outliers to the dataset
dt_full <- rbind(dt,c(1,1000),c(5,1998))   #adding two outliers
lm.full <- lm(y~x, data = dt_full)
summary(lm.full)

# (1c) Data visualization with the regression line
plot(dt_full, main = "Comparison of two regression lines",
     xlab = "x", 
     ylab = "y")
abline(a=coef(lm.dt)[1], 
       b= coef(lm.dt)[2], 
       col = "blue")  #the regression line without outliers
abline(a=coef(lm.full)[1],
       b= coef(lm.full)[2],
       col = "red") #the regression line with outliers
legend(-4,1500,c("Without outlier","With outlier"),
  col = c("blue", "red"),
  lwd = c(4, 4),
  cex = .9
)

## Question 2
library(arm)
library(Matching)
data(lalonde)

# This is the dataset for control group
lalonde_control <- lalonde[which(lalonde$treat == 0), ]
# This is the dataset for treatmetn group
lalonde_treat <- lalonde[which(lalonde$treat == 1), ]

#Regression model, using the whole data set to train
lm.lalonde <-
  lm(re78 ~ age + I(age^2) + educ + treat + I(treat*age) + re74+ re75,
     data = lalonde)
summary(lm.lalonde)

#Simulation
iterations <- 10000
sim.lalonde <- sim(lm.lalonde, n.sims = iterations)
sim.lalonde

#(a)
# Predict re78 for every TREATED unit of age for every set of coefficients holding at the means
simulated.ys_mean <- matrix(NA, nrow = iterations, ncol = length(
  min(lalonde$age):max(lalonde$age)))

mean.educ <- mean(lalonde_treat$educ)
mean.educ
mean.re74 <- mean(lalonde_treat$re74)
mean.re74
mean.re75 <- mean(lalonde_treat$re75)
mean.re75
for (age in min(lalonde$age):max(lalonde$age)) {
  Xs<- c(1, age, age^2, mean.educ, 1, 1*age, mean.re74, mean.re75)
  for (i in 1:iterations){
    simulated.ys_mean[i,age+1-min(lalonde$age)] <- sum(Xs*sim.lalonde@coef[i,])
  }
}

conf.intervals_treat <- apply(simulated.ys_mean, 2, quantile, probs = c(0.025, 0.975))
table_mean <- t(data.frame(conf.intervals_treat))
colnames(table_mean) <- c("Mean CI Lower Bound (2.5%)", "Mean CI Upper Bound(97.5%)")
table_mean <- data.frame(table_mean)
rownames(table_mean) <- min(lalonde$age):max(lalonde$age)
View(table_mean)

#Generate the figure for the prediction interval for each age
plot(x = c(1:100), y = c(1:100), type = "n", 
     xlim = c(min(lalonde$age),max(lalonde$age)), 
     ylim = c(2500,15000), 
     main = "Re78 by Age With Predictors Held at The Mean for TREATED units", 
     xlab = "Age", 
     ylab = "Re78")

for (age in min(lalonde$age):max(lalonde$age)) {
  segments(
    x0 = age,
    y0 = conf.intervals_treat[1, age - min(lalonde$age) + 1],
    x1 = age,
    y1 = conf.intervals_treat[2, age - min(lalonde$age) + 1],
    lwd = 2)
}

#(b)
# Predict re78 for every CONTROL unit of age for every set of coefficients holding at the means
simulated.ys_mean.control <- matrix(NA, nrow = iterations, ncol = length(
  min(lalonde$age):max(lalonde$age)))

mean.educ.control <- mean(lalonde_control$educ)
mean.educ.control
mean.re74.control <- mean(lalonde_control$re74)
mean.re74.control
mean.re75.control <- mean(lalonde_control$re75)
mean.re75.control
for (age in min(lalonde$age):max(lalonde$age)) {
  Xs<- c(1, age, age^2, mean.educ.control, 0, 0*age, mean.re74.control, mean.re75.control)
  for (i in 1:iterations){
    simulated.ys_mean.control[i,age+1-min(lalonde$age)] <- sum(Xs*sim.lalonde@coef[i,])
  }
}

conf.intervals_control <- apply(simulated.ys_mean.control, 2, quantile, probs = c(0.025, 0.975))
table_mean.control <- t(data.frame(conf.intervals_control))
colnames(table_mean.control) <- c("Mean CI Lower Bound (2.5%)", "Mean CI Upper Bound(97.5%)")
table_mean.control <- data.frame(table_mean.control)
rownames(table_mean.control) <- min(lalonde$age):max(lalonde$age)
View(table_mean.control)

#Generate the figure for the prediction interval for each age
plot(x = c(1:100), y = c(1:100), type = "n", 
     xlim = c(min(lalonde$age),max(lalonde$age)), 
     ylim = c(-1800,12000), 
     main = "Re78 by Age With Predictors Held at The Mean for CONTROL units", 
     xlab = "Age", 
     ylab = "Re78")

for (age in min(lalonde$age):max(lalonde$age)) {
  segments(
    x0 = age,
    y0 = conf.intervals_control[1, age - min(lalonde$age) + 1],
    x1 = age,
    y1 = conf.intervals_control[2, age - min(lalonde$age) + 1],
    lwd = 2)
}

#(c): treatment effect
# Predict re78 for every unit of age for every set of coefficients holding at the means
simulated.ys_mean.effect <- matrix(NA, nrow = iterations, ncol = length(
  min(lalonde$age):max(lalonde$age)))

mean.educ.effect <- mean(lalonde$educ)
mean.educ.effect
mean.re74.effect <- mean(lalonde$re74)
mean.re74.effect
mean.re75.effect <- mean(lalonde$re75)
mean.re75.effect
for (age in min(lalonde$age):max(lalonde$age)) {
  Xs_control<- c(1, age, age^2, mean.educ.effect, 0, 0*age, mean.re74.effect, mean.re75.effect)
  Xs_treat<- c(1, age, age^2, mean.educ.effect, 1, 1*age, mean.re74.effect, mean.re75.effect)
  for (i in 1:iterations){
    simulated.ys_mean.effect[i,age+1-min(lalonde$age)] <- (sum(Xs_treat*sim.lalonde@coef[i,])-sum(Xs_control*sim.lalonde@coef[i,]))
  }
}

conf.intervals_effect <- apply(simulated.ys_mean.effect, 2, quantile, probs = c(0.025, 0.975))
table_mean.effect <- t(data.frame(conf.intervals_effect))
colnames(table_mean.effect) <- c("Mean CI Lower Bound (2.5%)", "Mean CI Upper Bound(97.5%)")
table_mean.effect <- data.frame(table_mean.effect)
rownames(table_mean.effect) <- min(lalonde$age):max(lalonde$age)
View(table_mean.effect)

#Generate the figure for the prediction interval for each age
plot(x = c(1:100), y = c(1:100), type = "n", 
     xlim = c(min(lalonde$age),max(lalonde$age)), 
     ylim = c(-1100,10000), 
     main = "Treatment effect on Re78 by Age with Predictors Held at The Mean for all units", 
     xlab = "Age", 
     ylab = "Re78")

for (age in min(lalonde$age):max(lalonde$age)) {
  segments(
    x0 = age,
    y0 = conf.intervals_effect[1, age - min(lalonde$age) + 1],
    x1 = age,
    y1 = conf.intervals_effect[2, age - min(lalonde$age) + 1],
    lwd = 2)
}

#(d): treatment effect, prediction interval
# Predict re78 for every unit of age for every set of coefficients holding at the means
simulated.ys_median.effect.pred <- matrix(NA, nrow = iterations, ncol = length(
  min(lalonde$age):max(lalonde$age)))

median.educ.effect <- median(lalonde$educ)
median.educ.effect
median.re74.effect <- median(lalonde$re74)
median.re74.effect
median.re75.effect <- median(lalonde$re75)
median.re75.effect

for (age in min(lalonde$age):max(lalonde$age)) {
  Xs_control<- c(1, age, age^2, median.educ.effect, 0, 0*age, median.re74.effect, median.re75.effect)
  Xs_treat<- c(1, age, age^2, median.educ.effect, 1, 1*age, median.re74.effect, median.re75.effect)
  for (i in 1:iterations){
    simulated.ys_median.effect.pred[i,age+1-min(lalonde$age)] <- (sum(Xs_treat*sim.lalonde@coef[i,])-sum(Xs_control*sim.lalonde@coef[i,]))+rnorm(1, 0, sim.lalonde@sigma[i])
  }
}

conf.intervals_effect.pred <- apply(simulated.ys_median.effect.pred, 2, quantile, probs = c(0.025, 0.975))
table_mean.effect.pred <- t(data.frame(conf.intervals_effect.pred))
colnames(table_mean.effect.pred) <- c("Mean CI Lower Bound (2.5%)", "Mean CI Upper Bound(97.5%)")
table_mean.effect.pred <- data.frame(table_mean.effect.pred)
rownames(table_mean.effect.pred) <- min(lalonde$age):max(lalonde$age)
View(table_mean.effect.pred)

#Generate the figure for the prediction interval for each age
plot(x = c(1:100), y = c(1:100), type = "n", 
     xlim = c(min(lalonde$age),max(lalonde$age)), 
     ylim = c(-13000,19000), 
     main = "95% Prediction intervals for Treatment effect on Re78 by Age with Predictors Held at The Median for all units", 
     xlab = "Age", 
     ylab = "Re78")

for (age in min(lalonde$age):max(lalonde$age)) {
  segments(
    x0 = age,
    y0 = conf.intervals_effect.pred[1, age - min(lalonde$age) + 1],
    x1 = age,
    y1 = conf.intervals_effect.pred[2, age - min(lalonde$age) + 1],
    lwd = 2)
}


#Question 3
foo <- read.csv(url("https://tinyurl.com/y2prc9xq"))

##regression model
lm.afterschool <- lm(MATH_SCORE~TREATMENT, data=foo)
confint(lm.afterschool)[2,] #this is the analytical CI

##Bootstrapping 
coef.storage <- c()
set.seed(221)
for (i in 1:10000){
  index <- sample(nrow(foo),nrow(foo),replace=TRUE)
  bootstr.math <- foo$MATH_SCORE[index]
  bootstr.treatment <- foo$TREATMENT[index]
  lm.boot <- lm(bootstr.math~bootstr.treatment)
  coef.storage[i] <- lm.boot$coef[2]
}
quantile(coef.storage,probs=c(0.025,0.975))

##plot
hist(coef.storage, 
     main='Histogram of the bootstrapped estimates for the coefficient for treatment',
     xlab='Bootstrapped estimate',
     ylab='Frequency')
mean(coef.storage)
abline(v=mean(coef.storage),col='red')
abline(v=quantile(coef.storage,probs=c(0.025,0.975))[1],col="blue")
abline(v=quantile(coef.storage,probs=c(0.025,0.975))[2],col="blue")

##calculation
mean(coef.storage) - quantile(coef.storage, probs=c(.025,.975))[[1]] 
quantile(coef.storage, probs=c(.025,.975))[[2]] - mean(coef.storage)

#Question 4
set.seed(221)
boot.rsquared <- function(y, y.pred) {
  y_new <- na.omit(y)
  storage <- c()
  for (i in 1:100){
    index <- sample(length(y_new),length(y_new),replace=TRUE)
    bootstr.y <- y_new[index]
    bootstr.y.pred <- y.pred[index]
    # RSS (residual sum of squares) is the sum
    # squared value of deviations (difference) of the 
    # predicted ys from ys.
    rss <- sum((bootstr.y-bootstr.y.pred)^2)
    # TSS (total sum of squares) is the sum of the squared difference
    # between each true data point and the mean
    # of all data points
    tss <- sum((bootstr.y-mean(bootstr.y))^2)
    # R^2 = 1-RSS/TSS
    rsquared <- 1-rss/tss
    storage[i] <- rsquared
  }
  return(storage)
}

##test
boot.rsquared(foo$MATH_SCORE,predict.lm(lm.afterschool))
summary(lm.afterschool)$r.squared

#Question 5
library(boot)
foo5 <- read.csv(url("https://tinyurl.com/yx8tqf3k"))
set.seed(12345)
test_set_rows <- sample(1:length(foo5$age), 2000, replace = FALSE) 
training_data <- foo5[-test_set_rows,]
test_data <- foo5[test_set_rows,]
head(foo5)

##model 1
model1 <- glm(treat ~ age + education , data=training_data)
cv.err.1 <-cv.glm(training_data,model2)
cv.err.1$delta[1]
test.error.1 <- mean((test_data$treat - predict.glm(model1,test_data))^2)
test.error.1

##model 2
model2 <- glm(treat ~ age + education +black, data=training_data)
cv.err.2 <-cv.glm(training_data,model1)
cv.err.2$delta[1]
test.error.2 <- mean((test_data$treat - predict.glm(model2,test_data))^2)
test.error.2

##model 3
model3 <- glm(treat ~ age + education + black +hispanic , data=training_data)
cv.err.3 <-cv.glm(training_data,model3)
cv.err.3$delta[1]
test.error.3 <- mean((test_data$treat - predict.glm(model3,test_data))^2)
test.error.3

##model 4
model4 <- glm(treat ~ age + education + black +hispanic +re74 , data=training_data)
cv.err.4 <-cv.glm(training_data,model4)
cv.err.4$delta[1]
test.error.4 <- mean((test_data$treat - predict.glm(model4,test_data))^2)
test.error.4

##model 5
model5 <- glm(treat ~ age + education + black +hispanic +re74 + married + nodegree + re75 , data=training_data)
cv.err.5 <-cv.glm(training_data,model5)
cv.err.5$delta[1]
test.error.5 <- mean((test_data$treat - predict.glm(model5,test_data))^2)
test.error.5
